apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: delivery-service
  name: delivery-service
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: delivery-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: delivery-service
    spec:
      containers:
      - image: sxvi98/delivery-service:cc01584312e9513b42d65b7714d4bc71335d72d5
        imagePullPolicy: IfNotPresent
        name: delivery-service
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 5000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30