apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: delivery-service
  name: delivery-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: delivery-service
status:
  loadBalancer: {}